/*
 * ESP8266_UART.h
 *
 *  Created on: May 9, 2023
 *      Author: NEW
 */

#ifndef SRC_COMMUNICATION_ESP8266_UART_H_
#define SRC_COMMUNICATION_ESP8266_UART_H_



#endif /* SRC_COMMUNICATION_ESP8266_UART_H_ */
